### ISSUE TITLE
clear screen Linux

### ISSUE THREAD

**Issue by syyfff** [kelasweekend/whatsapp-py#1]
Fungsi clear screen tidak bekerja dengan baik untuk pengguna Linux, di karenakan Anda menggunakan ```cls```, yang mana itu bekerja di OS Windows. coba tambahkan fungsi clear screen untuk Linux. Terimakasih.

**Comment by kelasweekend** [comment]
terima kasih sarannya gan, segera saya update dan push ke repo ini kembali 👍
